#Obtain info. from tensors

In [1]:
import tensorflow as tf

In [2]:
tf.random.set_seed(1234)

tensor1 = tf.random.Generator.from_seed(1234)

tensor1 = tensor1.normal(shape = (3,4,5))

tensor1

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[ 0.9356609 ,  1.0854305 , -0.93788373, -0.5061547 ,
          1.3169702 ],
        [ 0.7137579 , -0.4126717 , -0.40257987,  2.0713255 ,
         -0.35911667],
        [ 0.3861619 ,  1.9897066 , -0.2823396 , -0.5135972 ,
         -0.8962833 ],
        [-0.0901652 , -0.73964226, -0.46269894,  0.42379895,
          1.1180195 ]],

       [[ 1.4442351 , -1.0771092 ,  0.9014347 , -0.14529487,
          1.173365  ],
        [ 1.510687  , -0.46714714,  1.3281798 ,  1.7365712 ,
         -1.5435543 ],
        [ 0.35064182,  0.5708492 , -1.8452454 ,  0.9243176 ,
          0.57233644],
        [-1.0959795 , -0.62557054,  0.686686  ,  0.4222773 ,
         -0.2146352 ]],

       [[-0.81243026, -1.1678637 ,  1.6384528 ,  1.187959  ,
         -2.5538385 ],
        [-0.39338952,  0.233341  , -1.6181145 , -0.8736809 ,
          0.05150718],
        [ 2.2328985 ,  2.8749912 ,  0.08306922, -0.9871888 ,
          0.47143334],
        [-1.7806206 ,

In [3]:
tensor1.shape

TensorShape([3, 4, 5])

In [12]:
tensor1.shape[0]

3

In [4]:
tensor1.ndim

3

In [5]:
tensor1[0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.9356609 ,  1.0854305 , -0.93788373, -0.5061547 ,  1.3169702 ],
       [ 0.7137579 , -0.4126717 , -0.40257987,  2.0713255 , -0.35911667],
       [ 0.3861619 ,  1.9897066 , -0.2823396 , -0.5135972 , -0.8962833 ],
       [-0.0901652 , -0.73964226, -0.46269894,  0.42379895,  1.1180195 ]],
      dtype=float32)>

In [6]:
tensor1[0, :3, 4]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 1.3169702 , -0.35911667, -0.8962833 ], dtype=float32)>

In [7]:
tensor1[-1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.81243026, -1.1678637 ,  1.6384528 ,  1.187959  , -2.5538385 ],
       [-0.39338952,  0.233341  , -1.6181145 , -0.8736809 ,  0.05150718],
       [ 2.2328985 ,  2.8749912 ,  0.08306922, -0.9871888 ,  0.47143334],
       [-1.7806206 , -0.27681163, -0.9240901 ,  1.3088665 ,  0.7826533 ]],
      dtype=float32)>

In [8]:
tf.size(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=60>

In [9]:
tensor1.dtype

tf.float32

#Indexing tensors

In [13]:
tensor1[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[ 0.9356609 ,  1.0854305 ],
        [ 0.7137579 , -0.4126717 ]],

       [[ 1.4442351 , -1.0771092 ],
        [ 1.510687  , -0.46714714]]], dtype=float32)>

In [17]:
tensor1[:1, :1, :-1]

<tf.Tensor: shape=(1, 1, 4), dtype=float32, numpy=
array([[[ 0.9356609 ,  1.0854305 , -0.93788373, -0.5061547 ]]],
      dtype=float32)>

In [18]:
tensor1[:1, :1, -1:]

<tf.Tensor: shape=(1, 1, 1), dtype=float32, numpy=array([[[1.3169702]]], dtype=float32)>

In [19]:
tensor1[-1, -1, :]

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-1.7806206 , -0.27681163, -0.9240901 ,  1.3088665 ,  0.7826533 ],
      dtype=float32)>

#Add extra dimensions

In [24]:
tensor1 = tensor1[..., tf.newaxis]

In [25]:
tensor1

<tf.Tensor: shape=(3, 4, 5, 1), dtype=float32, numpy=
array([[[[ 0.9356609 ],
         [ 1.0854305 ],
         [-0.93788373],
         [-0.5061547 ],
         [ 1.3169702 ]],

        [[ 0.7137579 ],
         [-0.4126717 ],
         [-0.40257987],
         [ 2.0713255 ],
         [-0.35911667]],

        [[ 0.3861619 ],
         [ 1.9897066 ],
         [-0.2823396 ],
         [-0.5135972 ],
         [-0.8962833 ]],

        [[-0.0901652 ],
         [-0.73964226],
         [-0.46269894],
         [ 0.42379895],
         [ 1.1180195 ]]],


       [[[ 1.4442351 ],
         [-1.0771092 ],
         [ 0.9014347 ],
         [-0.14529487],
         [ 1.173365  ]],

        [[ 1.510687  ],
         [-0.46714714],
         [ 1.3281798 ],
         [ 1.7365712 ],
         [-1.5435543 ]],

        [[ 0.35064182],
         [ 0.5708492 ],
         [-1.8452454 ],
         [ 0.9243176 ],
         [ 0.57233644]],

        [[-1.0959795 ],
         [-0.62557054],
         [ 0.686686  ],
         [ 0.42227

In [26]:
tensor2 = tensor1[tf.newaxis, ...]

In [27]:
tensor2

<tf.Tensor: shape=(1, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[ 0.9356609 ],
          [ 1.0854305 ],
          [-0.93788373],
          [-0.5061547 ],
          [ 1.3169702 ]],

         [[ 0.7137579 ],
          [-0.4126717 ],
          [-0.40257987],
          [ 2.0713255 ],
          [-0.35911667]],

         [[ 0.3861619 ],
          [ 1.9897066 ],
          [-0.2823396 ],
          [-0.5135972 ],
          [-0.8962833 ]],

         [[-0.0901652 ],
          [-0.73964226],
          [-0.46269894],
          [ 0.42379895],
          [ 1.1180195 ]]],


        [[[ 1.4442351 ],
          [-1.0771092 ],
          [ 0.9014347 ],
          [-0.14529487],
          [ 1.173365  ]],

         [[ 1.510687  ],
          [-0.46714714],
          [ 1.3281798 ],
          [ 1.7365712 ],
          [-1.5435543 ]],

         [[ 0.35064182],
          [ 0.5708492 ],
          [-1.8452454 ],
          [ 0.9243176 ],
          [ 0.57233644]],

         [[-1.0959795 ],
          [-0.62557054],
  

In [28]:
tf.expand_dims(tensor2, axis=0)

<tf.Tensor: shape=(1, 1, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[[ 0.9356609 ],
           [ 1.0854305 ],
           [-0.93788373],
           [-0.5061547 ],
           [ 1.3169702 ]],

          [[ 0.7137579 ],
           [-0.4126717 ],
           [-0.40257987],
           [ 2.0713255 ],
           [-0.35911667]],

          [[ 0.3861619 ],
           [ 1.9897066 ],
           [-0.2823396 ],
           [-0.5135972 ],
           [-0.8962833 ]],

          [[-0.0901652 ],
           [-0.73964226],
           [-0.46269894],
           [ 0.42379895],
           [ 1.1180195 ]]],


         [[[ 1.4442351 ],
           [-1.0771092 ],
           [ 0.9014347 ],
           [-0.14529487],
           [ 1.173365  ]],

          [[ 1.510687  ],
           [-0.46714714],
           [ 1.3281798 ],
           [ 1.7365712 ],
           [-1.5435543 ]],

          [[ 0.35064182],
           [ 0.5708492 ],
           [-1.8452454 ],
           [ 0.9243176 ],
           [ 0.57233644]],

          [[-1

In [29]:
tf.expand_dims(tensor2, axis=-1)

<tf.Tensor: shape=(1, 3, 4, 5, 1, 1), dtype=float32, numpy=
array([[[[[[ 0.9356609 ]],

          [[ 1.0854305 ]],

          [[-0.93788373]],

          [[-0.5061547 ]],

          [[ 1.3169702 ]]],


         [[[ 0.7137579 ]],

          [[-0.4126717 ]],

          [[-0.40257987]],

          [[ 2.0713255 ]],

          [[-0.35911667]]],


         [[[ 0.3861619 ]],

          [[ 1.9897066 ]],

          [[-0.2823396 ]],

          [[-0.5135972 ]],

          [[-0.8962833 ]]],


         [[[-0.0901652 ]],

          [[-0.73964226]],

          [[-0.46269894]],

          [[ 0.42379895]],

          [[ 1.1180195 ]]]],



        [[[[ 1.4442351 ]],

          [[-1.0771092 ]],

          [[ 0.9014347 ]],

          [[-0.14529487]],

          [[ 1.173365  ]]],


         [[[ 1.510687  ]],

          [[-0.46714714]],

          [[ 1.3281798 ]],

          [[ 1.7365712 ]],

          [[-1.5435543 ]]],


         [[[ 0.35064182]],

          [[ 0.5708492 ]],

          [[-1.8452454 ]],

  

In [30]:
tf.expand_dims(tensor2, axis=2)

<tf.Tensor: shape=(1, 3, 1, 4, 5, 1), dtype=float32, numpy=
array([[[[[[ 0.9356609 ],
           [ 1.0854305 ],
           [-0.93788373],
           [-0.5061547 ],
           [ 1.3169702 ]],

          [[ 0.7137579 ],
           [-0.4126717 ],
           [-0.40257987],
           [ 2.0713255 ],
           [-0.35911667]],

          [[ 0.3861619 ],
           [ 1.9897066 ],
           [-0.2823396 ],
           [-0.5135972 ],
           [-0.8962833 ]],

          [[-0.0901652 ],
           [-0.73964226],
           [-0.46269894],
           [ 0.42379895],
           [ 1.1180195 ]]]],



        [[[[ 1.4442351 ],
           [-1.0771092 ],
           [ 0.9014347 ],
           [-0.14529487],
           [ 1.173365  ]],

          [[ 1.510687  ],
           [-0.46714714],
           [ 1.3281798 ],
           [ 1.7365712 ],
           [-1.5435543 ]],

          [[ 0.35064182],
           [ 0.5708492 ],
           [-1.8452454 ],
           [ 0.9243176 ],
           [ 0.57233644]],

          [[

#Manipulating tensors (tensor operations)

***Basic operations***

In [37]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],

                      [[1,2,3],
                       [4,5,6],
                       [7,8,9]],

                      [[1,2,3],
                       [4,5,6],
                       [7,8,9]]])

tensor2 = tf.constant([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],

                      [[1,2,3],
                       [4,5,6],
                       [7,8,9]],

                      [[1,2,3],
                       [4,5,6],
                       [7,8,9]]])

In [32]:
tensor+10

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]], dtype=int32)>

In [33]:
tensor-10

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[-9, -8, -7],
        [-6, -5, -4],
        [-3, -2, -1]],

       [[-9, -8, -7],
        [-6, -5, -4],
        [-3, -2, -1]],

       [[-9, -8, -7],
        [-6, -5, -4],
        [-3, -2, -1]]], dtype=int32)>

In [34]:
tensor*3

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]],

       [[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]],

       [[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]]], dtype=int32)>

In [35]:
tensor/8

<tf.Tensor: shape=(3, 3, 3), dtype=float64, numpy=
array([[[0.125, 0.25 , 0.375],
        [0.5  , 0.625, 0.75 ],
        [0.875, 1.   , 1.125]],

       [[0.125, 0.25 , 0.375],
        [0.5  , 0.625, 0.75 ],
        [0.875, 1.   , 1.125]],

       [[0.125, 0.25 , 0.375],
        [0.5  , 0.625, 0.75 ],
        [0.875, 1.   , 1.125]]])>

Built-in function

In [36]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]], dtype=int32)>

In [39]:
tensor + tensor2

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]], dtype=int32)>

In [38]:
tensor - tensor2

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int32)>

In [42]:
tensor[0] * tensor[1]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)>

In [43]:
tensor[0] / tensor[1]

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])>

#Matrix multiplication

In [40]:
tf.matmul(tensor[0], tensor[1])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

In [44]:
tensor[0] @ tensor[1]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

Reshape

In [46]:
tf.reshape(tensor[0, :2, :3], shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [47]:
tf.transpose(tensor[0, :2, :3])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

#Dot Product of Vectors

In [50]:
tensor[0, 0, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [52]:
tf.transpose(tensor[0, 1, :])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [49]:
tf.tensordot(tensor[0, 0, :], tf.transpose(tensor[0, 1, :]), axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=32>