#Save and load the model:

In [1]:
import tensorflow as tf

X = tf.range(-100,100,5)
X

<tf.Tensor: shape=(40,), dtype=int32, numpy=
array([-100,  -95,  -90,  -85,  -80,  -75,  -70,  -65,  -60,  -55,  -50,
        -45,  -40,  -35,  -30,  -25,  -20,  -15,  -10,   -5,    0,    5,
         10,   15,   20,   25,   30,   35,   40,   45,   50,   55,   60,
         65,   70,   75,   80,   85,   90,   95], dtype=int32)>

In [2]:
y = X*3
y

<tf.Tensor: shape=(40,), dtype=int32, numpy=
array([-300, -285, -270, -255, -240, -225, -210, -195, -180, -165, -150,
       -135, -120, -105,  -90,  -75,  -60,  -45,  -30,  -15,    0,   15,
         30,   45,   60,   75,   90,  105,  120,  135,  150,  165,  180,
        195,  210,  225,  240,  255,  270,  285], dtype=int32)>

In [3]:
# Convert to tensors
X = tf.reshape(X, (-1, 1))  # Reshape to make it a column vector
y = tf.reshape(y, (-1, 1))

# Calculate the sizes for train, validation, and test sets
train_size = int(0.6 * len(X))
val_size = int(0.2 * len(X))

# Split the dataset
X_train, X_val, X_test = tf.split(X, [train_size, val_size, len(X) - train_size - val_size])
y_train, y_val, y_test = tf.split(y, [train_size, val_size, len(y) - train_size - val_size])

# Check the shapes of the tensors
print("X_train shape:", X_train.shape)
print("X_val shape:", X_val.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)
print("y_test shape:", y_test.shape)

X_train shape: (24, 1)
X_val shape: (8, 1)
X_test shape: (8, 1)
y_train shape: (24, 1)
y_val shape: (8, 1)
y_test shape: (8, 1)


#Model_1



In [17]:
import tensorflow as tf

# Create the model with Sequential API using .add method
model = tf.keras.Sequential(name="Model_1")
model.add(tf.keras.Input(shape=(1,)))  # The input layer
model.add(tf.keras.layers.Dense(200, activation='relu'))  # The hidden layer
model.add(tf.keras.layers.Dense(200, activation='relu'))  # The hidden layer
model.add(tf.keras.layers.Dense(1, activation=None))  # The output layer

# Compile the model
model.compile(loss="mae",
              optimizer=tf.keras.optimizers.SGD(),
              metrics=["mae"])

# Assuming X_tensor and y_tensor are your input and target tensors
# Fit the model
model.fit(X_train, y_train, epochs=400)

Epoch 1/400
1/1 [==============================] - 0s 459ms/step - loss: 138.0617 - mae: 138.0617
Epoch 2/400
1/1 [==============================] - 0s 13ms/step - loss: 109.0044 - mae: 109.0044
Epoch 3/400
1/1 [==============================] - 0s 11ms/step - loss: 57.5936 - mae: 57.5936
Epoch 4/400
1/1 [==============================] - 0s 10ms/step - loss: 156.9125 - mae: 156.9125
Epoch 5/400
1/1 [==============================] - 0s 13ms/step - loss: 134.0192 - mae: 134.0192
Epoch 6/400
1/1 [==============================] - 0s 12ms/step - loss: 132.4639 - mae: 132.4639
Epoch 7/400
1/1 [==============================] - 0s 11ms/step - loss: 130.4769 - mae: 130.4769
Epoch 8/400
1/1 [==============================] - 0s 15ms/step - loss: 126.5256 - mae: 126.5256
Epoch 9/400
1/1 [==============================] - 0s 12ms/step - loss: 117.9220 - mae: 117.9220
Epoch 10/400
1/1 [==============================] - 0s 10ms/step - loss: 94.6682 - mae: 94.6682
Epoch 11/400
1/1 [==============

In [18]:
model.summary()

Model: "Model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 200)               400       
                                                                 
 dense_13 (Dense)            (None, 200)               40200     
                                                                 
 dense_14 (Dense)            (None, 1)                 201       
                                                                 
Total params: 40801 (159.38 KB)
Trainable params: 40801 (159.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.predict([100])

1/1 [==============================] - 0s 75ms/step


array([[304.48703]], dtype=float32)

Saving our model supports us for deploying it in other environments

Formats:
1. The SavedModel format
2. The HDF5 format
3. The TensorFlow Checkpoint format
4. The TensorFlow Lite format

#1. The SavedModel format

In [43]:
#Mount the google drive connection to our dataset
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [31]:
# Save model
model.save('/content/drive/My Drive/Colab Notebooks/Tensorflow Notes/models')

# Load model
loaded_model = tf.keras.models.load_model("/content/drive/My Drive/Colab Notebooks/Tensorflow Notes/models")

In [32]:
loaded_model.predict([100])

1/1 [==============================] - 0s 73ms/step


array([[304.48703]], dtype=float32)

In [33]:
model_preds = model.predict(X_test)
loaded_model_preds = loaded_model.predict(X_test)

model_preds == loaded_model_preds

1/1 [==============================] - 0s 55ms/step


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#2. The HDF5 format

In [34]:
model.save('/content/drive/My Drive/Colab Notebooks/Tensorflow Notes/model2/my_model.h5')
loaded_model = tf.keras.models.load_model("/content/drive/My Drive/Colab Notebooks/Tensorflow Notes/model2/my_model.h5")

In [35]:
loaded_model.predict([100])

1/1 [==============================] - 0s 74ms/step


array([[304.48703]], dtype=float32)

In [36]:
model_preds = model.predict(X_test)
loaded_model_preds = loaded_model.predict(X_test)

model_preds == loaded_model_preds

1/1 [==============================] - 0s 59ms/step


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#3. The Tensorflow Checkpoint format:
* This format saves only the model weights without the model architecture.
* It's useful when you want to continue training from where you left off or when you need to save checkpoints during training.

In [26]:
model.save_weights("/content/drive/My Drive/Colab Notebooks/Tensorflow Notes/model3")
model.load_weights("/content/drive/My Drive/Colab Notebooks/Tensorflow Notes/model3")

In [27]:
model.predict([100])

1/1 [==============================] - 0s 60ms/step


array([[304.48703]], dtype=float32)

#4. TensorFlow Lite format:

* If you intend to deploy your model on mobile or embedded devices, you might need to convert it to TensorFlow Lite format.
* TensorFlow Lite is designed for running machine learning models on edge devices with limited computational resources.

In [28]:
# Convert model to TensorFlow Lite format
converter = tf.lite.TFLiteConverter.from_saved_model("/content/drive/My Drive/Colab Notebooks/Tensorflow Notes/models")
tflite_model = converter.convert()

# Save TensorFlow Lite model
with open("model.tflite", "wb") as f:
    f.write(tflite_model)

#Download a model (Or any file) form Google Colab

In [37]:
from google.colab import files
files.download('/content/drive/My Drive/Colab Notebooks/Tensorflow Notes/models')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

!cp is for copy files

In [46]:
!ls "/content/drive/MyDrive/Colab Notebooks/Tensorflow Notes/models"

assets	fingerprint.pb	keras_metadata.pb  saved_model.pb  variables
