#Change the DataType of a Tensor

In [1]:
import tensorflow as tf

In [3]:
tensor = tf.constant([[1,2],
                      [3,4]])

tensor.dtype

tf.int32

In [4]:
tensor2 = tf.constant([[1.,2.],
                      [3.,4.]])

tensor2.dtype

tf.float32

In [5]:
tf.cast(tensor, dtype=tf.int16)

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4]], dtype=int16)>

In [6]:
tf.cast(tensor, dtype=tf.int8)

<tf.Tensor: shape=(2, 2), dtype=int8, numpy=
array([[1, 2],
       [3, 4]], dtype=int8)>

In [10]:
tf.cast(tensor, dtype=tf.int64)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

In [7]:
tf.cast(tensor2, dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [11]:
tf.cast(tensor2, dtype=tf.float64)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

#Aggregating tensors

Condensing them fro mmultiple values down to a smaller amount of values.

Get the Abs of the tensor

In [12]:
tensor = tf.constant([-1., -2.])
abs_tensor = tf.abs(tensor)
abs_tensor

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [14]:
import numpy as np

tensor = tf.constant(np.random.randint(0,150,size=300))
tensor

<tf.Tensor: shape=(300,), dtype=int64, numpy=
array([139,  62,  38, 131, 108,  42,  36,  54, 103,  22,  20, 107,  74,
        75, 140,  67, 135,  67, 116,  14,  62,  29,  75,  50, 147,  16,
        66, 128,  23,  71, 116, 116,  30,   8,  62,  54,  92,  77,  33,
       135, 112,  77,  43,  83,  80,   4,  88,  60, 123,  24,  72, 124,
        84,  38, 143,  67,  70, 104,   2,  58,  86, 126,   5,   4, 103,
       122,  41, 103,  41,  73,  15,  78, 117,   3,  13,  83, 109, 120,
        91, 134,  58,  12,   5,  78, 116, 110,  65, 131, 141,  86, 127,
        65, 100,  32, 126,  37,  63,  56,  56,  52,  72,  67, 112,  33,
        84,   5,  15,  84, 141,  40,  98,  44,  81,  35,  34, 113,   6,
       113,  25,  40,  63,  66,  25, 107,  20, 125,  60,  67,  98, 121,
        66,  20,   2,  59,  77,  45, 136,  36,  54,  73,  76,  36, 101,
        90, 144,  24,  39,   6,   0,  53,  48,  23,  17, 142,  49,  78,
        45,  77,  64, 144,  98,  61, 129,   1, 139,  36, 111,  50,  26,
        32, 114,  

In [15]:
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([300]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=300>)

Find the minimum value

In [16]:
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

Find the maximum value

In [17]:
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=149>

Find the mean

In [18]:
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=72>

Find the sum

In [19]:
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=21881>

Find the variance

In [21]:
tf.reduce_mean(tf.square(tensor - tf.reduce_mean(tensor)))

<tf.Tensor: shape=(), dtype=int64, numpy=1838>

In [27]:
import tensorflow_probability as tfp
tfp.stats.variance(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=1838>

Find the standard deviation

In [29]:
tf.sqrt(tf.cast(tf.reduce_mean(tf.square(tensor - tf.reduce_mean(tensor))), dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=42.871902>

In [32]:
tf.math.reduce_std(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=42.870262>

#Find the positional maximum and minimum

In [33]:
tf.random.set_seed(43)
tensor = tf.random.uniform(shape=[100])
tensor

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.2733041 , 0.5020257 , 0.6628481 , 0.6473899 , 0.3857293 ,
       0.36172044, 0.5412978 , 0.48597205, 0.8773687 , 0.19192028,
       0.9264002 , 0.89626896, 0.6672703 , 0.47216296, 0.22052324,
       0.88224113, 0.21332026, 0.3742751 , 0.6198429 , 0.67401516,
       0.33629417, 0.04864144, 0.00223255, 0.9375315 , 0.1595205 ,
       0.76488817, 0.5631764 , 0.48775423, 0.4250028 , 0.29910493,
       0.8409952 , 0.6727512 , 0.00153816, 0.4085456 , 0.9261861 ,
       0.18742752, 0.60272205, 0.99417937, 0.42423892, 0.27978897,
       0.9430332 , 0.80545497, 0.06359637, 0.56783044, 0.26592016,
       0.98973536, 0.5452112 , 0.11514163, 0.53635466, 0.6935723 ,
       0.7949647 , 0.7486353 , 0.6800747 , 0.6137345 , 0.87506485,
       0.93296814, 0.04352331, 0.3685708 , 0.5699148 , 0.07984412,
       0.6718762 , 0.708205  , 0.8574375 , 0.21595812, 0.5249181 ,
       0.8443382 , 0.48224807, 0.3207147 , 0.22593236, 0.624475  ,
       0.65453

Largest value position

In [34]:
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [35]:
tensor[tf.argmax(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.99417937>

In [40]:
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99417937>

In [43]:
assert tensor[tf.argmax(tensor)] == tf.reduce_max(tensor)

In [42]:
tensor[tf.argmax(tensor)] == tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

Smallest value position

In [36]:
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=32>

In [38]:
tensor[tf.argmin(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0015381575>

In [39]:
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0015381575>

In [44]:
assert tensor[tf.argmin(tensor)] == tf.reduce_min(tensor)

In [45]:
tensor[tf.argmin(tensor)] == tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

#Squeezing a tensor

Remove all single dimensions

In [48]:
tf.random.set_seed(42)

tensor = tf.constant(tf.random.uniform(shape=[100]), shape=(1,1,1,1,1,1,1,1,100))

In [49]:
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 1, 1, 1, 1, 100), dtype=float32, numpy=
array([[[[[[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255,
               0.03366041, 0.68467236, 0.74011743, 0.8724445 ,
               0.22632635, 0.22319686, 0.3103881 , 0.7223358 ,
               0.13318717, 0.5480639 , 0.5746088 , 0.8996835 ,
               0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
               0.72942245, 0.54583454, 0.10756552, 0.6767061 ,
               0.6602763 , 0.33695042, 0.60141766, 0.21062577,
               0.8527372 , 0.44062173, 0.9485276 , 0.23752594,
               0.81179297, 0.5263394 , 0.494308  , 0.21612847,
               0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
               0.23764038, 0.7817228 , 0.9671384 , 0.06870162,
               0.79873943, 0.66028714, 0.5871513 , 0.16461694,
               0.7381023 , 0.32054043, 0.6073899 , 0.46523476,
               0.97803545, 0.7223145 , 0.32347047, 0.82577336,
               0.4976915 , 0.19483674, 0.758874

In [50]:
tensor_squeezed = tf.squeeze(tensor)
tensor_squeezed, tensor_squeezed.shape

(<tf.Tensor: shape=(100,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043,
        0.6073899 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
        0.82577336, 0.4976915 , 0.19483674, 0.7588748 , 0.3380444 ,
        0.28128064, 0.31513572, 0.60670924, 0.7498598 , 0.5016055 ,
        0.18282163, 0.13179815, 0.64636123, 0.9559475 , 0.6670735 ,

#One-hot encoding tensors

In [52]:
list_ = [0,0,1,2,1,3,3,1,2,4]
tf.one_hot(list_, depth=len(set(list_)))

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [53]:
tf.one_hot(list_, depth=len(set(list_)), on_value='Yes', off_value='No')

<tf.Tensor: shape=(10, 5), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No', b'No'],
       [b'Yes', b'No', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No', b'No'],
       [b'No', b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes', b'No'],
       [b'No', b'Yes', b'No', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'No', b'No', b'Yes']], dtype=object)>