#Squaring, log, square root

In [1]:
import tensorflow as tf

In [6]:
tf.random.set_seed(41)

tensor = tf.random.uniform(shape=(3,3))

In [7]:
tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.5692048 , 0.6666248 , 0.32513022],
       [0.09477615, 0.1430676 , 0.9487461 ],
       [0.26147044, 0.53215694, 0.5716516 ]], dtype=float32)>

In [8]:
tensor2 = tf.range(1,100)
tensor2

<tf.Tensor: shape=(99,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int32)>

Square a tensor

In [9]:
tf.square(tensor)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.3239941 , 0.4443886 , 0.10570966],
       [0.00898252, 0.02046834, 0.9001191 ],
       [0.06836679, 0.28319103, 0.32678553]], dtype=float32)>

In [10]:
tf.square(tensor2)

<tf.Tensor: shape=(99,), dtype=int32, numpy=
array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025,
       3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356,
       4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929,
       6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744,
       7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801],
      dtype=int32)>

Find the square root of a tensor

In [11]:
tf.sqrt(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.75445664, 0.8164709 , 0.57020193],
       [0.30785736, 0.3782428 , 0.974036  ],
       [0.5113418 , 0.7294909 , 0.75607646]], dtype=float32)>

In [12]:
tf.sqrt(tf.cast(tensor2, dtype=tf.float32))

<tf.Tensor: shape=(99,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       , 3.1622777, 3.3166249, 3.4641016,
       3.6055512, 3.7416575, 3.8729835, 4.       , 4.1231055, 4.2426405,
       4.358899 , 4.472136 , 4.582576 , 4.690416 , 4.7958317, 4.8989797,
       5.       , 5.0990195, 5.196152 , 5.2915025, 5.3851647, 5.477226 ,
       5.5677643, 5.656854 , 5.7445626, 5.8309517, 5.91608  , 6.       ,
       6.0827627, 6.164414 , 6.244998 , 6.3245554, 6.4031243, 6.4807405,
       6.5574384, 6.6332498, 6.708204 , 6.78233  , 6.8556547, 6.928203 ,
       7.       , 7.071068 , 7.1414285, 7.2111025, 7.28011  , 7.3484693,
       7.4161983, 7.483315 , 7.5498343, 7.615773 , 7.6811457, 7.745967 ,
       7.81025  , 7.8740077, 7.937254 , 8.       , 8.062258 , 8.124039 ,
       8.185352 , 8.246211 , 8.306623 , 8.3666   , 8.426149 , 8.485281 ,
       8.5440035, 8.602325 , 8.6602545, 8.717798 , 8.774964 , 8.83176  ,
    

Find the log of a tensor

In [15]:
tf.math.log(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.56351495, -0.40552792, -1.1235294 ],
       [-2.3562374 , -1.944438  , -0.05261407],
       [-1.341434  , -0.6308168 , -0.5592256 ]], dtype=float32)>

In [16]:
tf.math.log(tf.cast(tensor2, dtype=tf.float32))

<tf.Tensor: shape=(99,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
       2.944439 , 2.9957323, 3.0445225, 3.0910425, 3.1354942, 3.1780539,
       3.218876 , 3.2580965, 3.295837 , 3.3322046, 3.3672957, 3.4011974,
       3.4339871, 3.465736 , 3.4965076, 3.5263605, 3.5553482, 3.583519 ,
       3.610918 , 3.637586 , 3.6635616, 3.6888795, 3.713572 , 3.7376697,
       3.7612002, 3.7841897, 3.8066626, 3.8286414, 3.8501477, 3.871201 ,
       3.8918204, 3.912023 , 3.9318256, 3.9512436, 3.9702919, 3.988984 ,
       4.0073333, 4.0253515, 4.0430512, 4.060443 , 4.0775375, 4.0943446,
       4.1108737, 4.1271343, 4.1431346, 4.158883 , 4.1743875, 4.189655 ,
       4.204693 , 4.2195077, 4.2341065, 4.248495 , 4.26268  , 4.276666 ,
       4.2904596, 4.304065 , 4.317488 , 4.3307333, 4.3438053, 4.356709 ,
    

#Tensors and Numpy

In [18]:
import numpy as np
tensor_numpy = tf.constant(np.array([1,2,3,4,5]))
tensor_numpy

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

In [19]:
np.array(tensor_numpy), type(np.array(tensor_numpy))

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [20]:
tensor_numpy.numpy(), type(tensor_numpy.numpy())

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [22]:
tensor_numpy = tf.constant([1.])
tensor_numpy.numpy()[0]

1.0

In [24]:
numpy_tensor = tf.constant(np.array((1., 2., 3.)))
built_in_tensor = tf.constant((1., 2., 3.))

numpy_tensor.dtype, built_in_tensor.dtype

(tf.float64, tf.float32)